import importlib
import pathlib
import sys
import tempfile
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))


class KimtomaMarkGeneratorTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.generator = importlib.import_module("gen_kimtoma_mark")
        cls.rows = cls.generator.build_rows(ROOT / "src/images/KimtomaMark120.svg")

    def test_dimensions_packed_size_and_binary_pixels(self):
        self.assertEqual(120, len(self.rows))
        self.assertTrue(all(len(row) == 120 for row in self.rows))
        self.assertTrue(all(pixel in (0, 1) for row in self.rows for pixel in row))
        self.assertEqual(1800, len(self.generator.pack(self.rows)))

    def test_packed_pixels_render_upright_in_portrait(self):
        packed = self.generator.pack(self.rows)
        physical_rows = []
        for y in range(120):
            row = []
            for x in range(120):
                byte = packed[y * 15 + x // 8]
                row.append((byte >> (7 - x % 8)) & 1)
            physical_rows.append(row)

        # The X4/simulator presents the physical framebuffer rotated 90 degrees
        # clockwise. The generated bytes must compensate so the approved SVG
        # remains upright in the logical portrait screen.
        portrait_rows = [
            [physical_rows[119 - x][y] for x in range(120)]
            for y in range(120)
        ]
        self.assertEqual(self.rows, portrait_rows)

    def test_black_geometry_is_centered(self):
        black = [(x, y) for y, row in enumerate(self.rows) for x, pixel in enumerate(row) if pixel == 0]
        min_x = min(x for x, _ in black)
        max_x = max(x for x, _ in black)
        min_y = min(y for _, y in black)
        max_y = max(y for _, y in black)
        self.assertLessEqual(abs((min_x + max_x) / 2 - 59.5), 2)
        self.assertLessEqual(abs((min_y + max_y) / 2 - 59.5), 2)

    def test_two_nostrils_survive_as_separate_components(self):
        pixels = {
            (x, y)
            for y in range(84, 86)
            for x in range(52, 68)
            if self.rows[y][x] == 0
        }
        components = []
        while pixels:
            stack = [pixels.pop()]
            component = set(stack)
            while stack:
                x, y = stack.pop()
                for neighbor in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
                    if neighbor in pixels:
                        pixels.remove(neighbor)
                        component.add(neighbor)
                        stack.append(neighbor)
            components.append(component)
        self.assertEqual(2, len(components))
        self.assertTrue(all(len(component) >= 6 for component in components))

    def test_checked_in_header_is_deterministic(self):
        packed = self.generator.pack(self.rows)
        with tempfile.TemporaryDirectory() as directory:
            generated = pathlib.Path(directory) / "KimtomaMark120.h"
            self.generator.write_header(packed, generated)
            expected = ROOT / "src/images/KimtomaMark120.h"
            self.assertEqual(expected.read_bytes(), generated.read_bytes())


if __name__ == "__main__":
    unittest.main()
